apiVersion: networktopology.diktyo.x-k8s.io/v1alpha1
kind: NetworkTopology
metadata:
  name: nt-cluster
  namespace: default
spec:
  configmapName: "netperfMetrics"
  weights:
    - name: "UserDefined"
      topologyList:
        - topologyKey: "topology.kubernetes.io/region"
          originList:
            - origin: "us-east-1"
              costList:
                - destination: "us-west-1"
                  networkCost: 200
                  bandwidthAllocated: "1Gi"
                  bandwidthCapacity: "10Gi"
            - origin: "us-west-1"
              costList:
                - destination: "us-east-1"
                  networkCost: 200
                  bandwidthAllocated: "1Gi"
                  bandwidthCapacity: "10Gi"
        - topologyKey: "topology.kubernetes.io/zone"
          originList:
            - origin: "z1"
              costList:
                - destination: "z2"
                  bandwidthCapacity: "1Gi"
                  networkCost: 50
            - origin: "z2"
              costList:
                - destination: "z1"
                  bandwidthCapacity: "1Gi"
                  networkCost: 50
            - origin: "z3"
              costList:
                - destination: "z4"
                  bandwidthCapacity: "1Gi"
                  networkCost: 100
            - origin: "z4"
              costList:
                - destination: "z3"
                  bandwidthCapacity: "1Gi"
                  networkCost: 100