apiVersion: batch/v1
kind: Job
metadata:
  name: mnist0
spec:
  parallelism: 4
  completions: 4
  template:
    metadata:
      labels:
        app: mnist
        scheduling.x-k8s.io/pod-group: mg1
    spec:
      initContainers:
      - name: rank-finder
        image: appropriate/curl
        command: ["/bin/sh", "-c"]
        args:
        - >
          set -e;
          RANK=$(kubectl get pods -l app=mnist -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | grep -n $(hostname) | cut -d: -f1);
          echo $RANK > /mnt/rank/rank.txt;
        volumeMounts:
        - name: rank-volume
          mountPath: /mnt/rank
      containers:
      - name: mnist
        image: jinnkenny99/dist-mnist:latest
        env:
        - name: WORLD_SIZE
          value: "4"
        - name: RANK
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: mnist-pvc
          mountPath: /mnt/data
        - name: rank-volume
          mountPath: /mnt/rank
      volumes:
      - name: mnist-pvc
        persistentVolumeClaim:
          claimName: mnist-pvc
      - name: rank-volume
        emptyDir: {}
      schedulerName: scheduler-plugins-scheduler
      restartPolicy: Never
      