apiVersion: batch/v1
kind: Job
metadata:
  name: mnist0
spec:
  template:
    metadata:
      labels:
        app: mnist
        scheduling.x-k8s.io/pod-group: mg1
    spec:
      containers:
      - name: mnist
        image: jinnkenny99/dist-mnist:latest
        env:
        - name: WORLD_SIZE
          value: "2"
        - name: RANK
          value: "0"
        volumeMounts:
        - name: mnist-pvc
          mountPath: /mnt/data
      volumes:
      - name: mnist-pvc
        persistentVolumeClaim:
          claimName: mnist-pvc
      schedulerName: scheduler-plugins-scheduler
      restartPolicy: Never
      