kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
- role: control-plane
  image: kindest/node:v1.21.1
  extraPortMappings:
  - containerPort: 30000
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: kindest/node:v1.21.1
  extraPortMappings:
  - containerPort: 30001
    hostPort: 81
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: kindest/node:v1.21.1
  extraPortMappings:
  - containerPort: 30002
    hostPort: 82
    listenAddress: "0.0.0.0"
    protocol: TCP