apiVersion: networktopology.diktyo.x-k8s.io/v1alpha1
kind: NetworkTopology
metadata:
  name: net-topology-test
  namespace: default
spec:
  configmapName: "netperfMetrics"
  weights:
    - name: "UserDefined"
      topologyList: # Define weights between regions or between zones 
        - topologyKey: "topology.kubernetes.io/region" # region costs
          originList:
            - origin: "zone-a"
              costList:
                - destination: "zone-b"
                  networkCost: 10
                  bandwidthAllocated: "100Mi"
                  bandwidthCapacity: "1Gi"
                - destination: "zone-c"
                  networkCost: 20
                  bandwidthAllocated: "50Mi"
                  bandwidthCapacity: "500Mi"
            - origin: "zone-b"
              costList:
                - destination: "zone-a"
                  networkCost: 10
                  bandwidthAllocated: "100Mi"
                  bandwidthCapacity: "1Gi"
                - destination: "zone-c"
                  networkCost: 20
                  bandwidthAllocated: "50Mi"
                  bandwidthCapacity: "500Mi"
            - origin: "zone-c"
              costList:
                - destination: "zone-a"
                  networkCost: 20
                  bandwidthAllocated: "50Mi"
                  bandwidthCapacity: "500Mi"
                - destination: "zone-b"
                  networkCost: 20
                  bandwidthAllocated: "50Mi"
                  bandwidthCapacity: "500Mi"