kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
- role: control-plane
  image: kindest/node:v1.21.1
  extraPortMappings:
  - containerPort: 30000
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        kube-reserved: cpu=500m,memory=1Gi
        system-reserved: cpu=500m,memory=1Gi
- role: worker
  image: kindest/node:v1.21.1
  extraPortMappings:
  - containerPort: 30001
    hostPort: 81
    listenAddress: "0.0.0.0"
    protocol: TCP
  extraConfig:
    kind: KubeletConfiguration
    kubeReserved:
      cpu: "500m"
      memory: "1Gi"
    systemReserved:
      cpu: "500m"
      memory: "1Gi"
    evictionHard:
      memory.available: "200Mi"
- role: worker
  image: kindest/node:v1.21.1
  extraPortMappings:
  - containerPort: 30002
    hostPort: 82
    listenAddress: "0.0.0.0"
    protocol: TCP
  extraConfig:
    kind: KubeletConfiguration
    kubeReserved:
      cpu: "500m"
      memory: "2Gi"
    systemReserved:
      cpu: "500m"
      memory: "2Gi"
    evictionHard:
      memory.available: "400Mi"
- role: worker
  image: kindest/node:v1.21.1
  extraPortMappings:
  - containerPort: 30003
    hostPort: 83
    listenAddress: "0.0.0.0"
    protocol: TCP
  extraConfig:
    kind: KubeletConfiguration
    kubeReserved:
      cpu: "1"
      memory: "2Gi"
    systemReserved:
      cpu: "1"
      memory: "2Gi"
    evictionHard:
      memory.available: "800Mi"
- role: worker
  image: kindest/node:v1.21.1
  extraPortMappings:
  - containerPort: 30004
    hostPort: 84
    listenAddress: "0.0.0.0"
    protocol: TCP
  extraConfig:
    kind: KubeletConfiguration
    kubeReserved:
      cpu: "1"
      memory: "2Gi"
    systemReserved:
      cpu: "1"
      memory: "2Gi"
    evictionHard:
      memory.available: "800Mi"
- role: worker
  image: kindest/node:v1.21.1
  extraPortMappings:
  - containerPort: 30004
    hostPort: 85
    listenAddress: "0.0.0.0"
    protocol: TCP
  extraConfig:
    kind: KubeletConfiguration
    kubeReserved:
      cpu: "500m"
      memory: "4Gi"
    systemReserved:
      cpu: "500m"
      memory: "4Gi"
    evictionHard:
      memory.available: "1.6Gi"
- role: worker
  image: kindest/node:v1.21.1
  extraPortMappings:
  - containerPort: 30004
    hostPort: 86
    listenAddress: "0.0.0.0"
    protocol: TCP
  extraConfig:
    kind: KubeletConfiguration
    kubeReserved:
      cpu: "1"
      memory: "2Gi"
    systemReserved:
      cpu: "1"
      memory: "2Gi"
    evictionHard:
      memory.available: "1.6Gi"
