apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  volumes:
  - name: mnist-data  # Name for the volume reference
    persistentVolumeClaim:
      claimName: mnist-pvc  # The name of the PVC to mount
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: mnist-data  # Reference to the volume above
      mountPath: /mnt/data  # Desired mount path inside the container
  hostNetwork: true
  dnsPolicy: Default