# permissions for end users to edit distributedjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: distributedjob-editor-role
rules:
- apiGroups:
  - batch.ddl.com
  resources:
  - distributedjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.ddl.com
  resources:
  - distributedjobs/status
  verbs:
  - get
