---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.ddl.com
  resources:
  - distributedjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.ddl.com
  resources:
  - distributedjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.ddl.com
  resources:
  - distributedjobs/status
  verbs:
  - get
  - patch
  - update
