apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 10Gi  # Adjust size as needed
  accessModes:
    - ReadWriteOnce  # Typically, Prometheus requires ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Policy for reclaiming the volume
  storageClassName: prometheus-storage  # Name of the storage class
  # Using a hostPath for demonstration; in production, use an EBS or another storage type
  hostPath:  
    path: /data/prometheus  # Path where data will be stored on the host

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  namespace: monitoring  kubectl apply --save-config -f pvc.yaml  # Specify the namespace
spec:
  accessModes:
    - ReadWriteOnce  # Match the PV access mode
  resources:
    requests:
      storage: 10Gi  # This should match the PV size
  storageClassName: prometheus-storage  # Ensure this matches the PV's storage class
