kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
- role: control-plane
  image: kindest/node:v1.26.15
  extraPortMappings:
  - containerPort: 30000
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: kindest/node:v1.26.15
  extraPortMappings:
  - containerPort: 30001
    hostPort: 81
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: kindest/node:v1.26.15
  extraPortMappings:
  - containerPort: 30002
    hostPort: 82
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: kindest/node:v1.26.15
  extraPortMappings:
  - containerPort: 30003
    hostPort: 83
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: kindest/node:v1.26.15
  extraPortMappings:
  - containerPort: 30004
    hostPort: 84
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: kindest/node:v1.26.15
  extraPortMappings:
  - containerPort: 30005
    hostPort: 85
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: kindest/node:v1.26.15
  extraPortMappings:
  - containerPort: 30006
    hostPort: 86
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: kindest/node:v1.26.15
  extraPortMappings:
  - containerPort: 30007
    hostPort: 87
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: kindest/node:v1.26.15
  extraPortMappings:
  - containerPort: 30008
    hostPort: 88
    listenAddress: "0.0.0.0"
    protocol: TCP