apiVersion: apps/v1
kind: Deployment
metadata:
  name: p1
  namespace: default
  labels:
    app: p1
    appgroup.diktyo.k8s.io: a1
    appgroup.diktyo.k8s.io.workload: p1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p1
  template:
    metadata:
      labels:
        app: p1
        appgroup.diktyo.k8s.io: a1
        appgroup.diktyo.k8s.io.workload: p1
    spec:
      containers:
      - name: p1-container
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2
  namespace: default
  labels:
    app: p2
    appgroup.diktyo.k8s.io: a1
    appgroup.diktyo.k8s.io.workload: p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2
  template:
    metadata:
      labels:
        app: p2
        appgroup.diktyo.k8s.io: a1
        appgroup.diktyo.k8s.io.workload: p2
    spec:
      containers:
      - name: p2-container
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: p3
  namespace: default
  labels:
    app: p3
    appgroup.diktyo.k8s.io: a1
    appgroup.diktyo.k8s.io.workload: p3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p3
  template:
    metadata:
      labels:
        app: p3
        appgroup.diktyo.k8s.io: a1
        appgroup.diktyo.k8s.io.workload: p3
    spec:
      containers:
      - name: p3-container
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432
