apiVersion: v1
kind: Pod
metadata:
  name: mnist-init-pod
spec:
  containers:
  - name: mnist-downloader
    image: python:3.8
    command: ["sh", "-c"]
    args:
      - |
        python -m ensurepip --upgrade && \
        pip install torch torchvision && \
        python -c "
        import torchvision.datasets as datasets;
        import torchvision.transforms as transforms;
        datasets.MNIST('/mnt/data', train=True, download=True, transform=transforms.ToTensor());
        datasets.MNIST('/mnt/data', train=False, download=True, transform=transforms.ToTensor());"
    volumeMounts:
    - name: mnist-storage
      mountPath: /mnt/data
  restartPolicy: OnFailure
  volumes:
  - name: mnist-storage
    persistentVolumeClaim:
      claimName: mnist-pvc
